version: '3.4'
networks:
  pgnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24

services:
  pg10:
    image: "postgres:10"
    restart: on-failure
    expose:
      - 5432
    ports:
      - "15010:5432"
    environment:
      - TZ=Europe/Moscow
      - PGTZ=Europe/Moscow
      - POSTGRES_DB=pgdb
      - POSTGRES_USER=pgdev
      - POSTGRES_PASSWORD=pgdev
    volumes:
      - "./_db/pg10:/var/lib/postgresql/data"
    networks:
      - pgnet
  pg11:
    image: "postgres:11"
    restart: on-failure
    expose:
      - 5432
    ports:
      - "15011:5432"
    environment:
      - TZ=Europe/Moscow
      - PGTZ=Europe/Moscow
      - POSTGRES_DB=pgdb
      - POSTGRES_USER=pgdev
      - POSTGRES_PASSWORD=pgdev
    volumes:
      - "./_db/pg11:/var/lib/postgresql/data"
    networks:
      - pgnet
  pg12:
      image: "postgres:12"
      restart: on-failure
      expose:
        - 5432
      ports:
        - "15012:5432"
      environment:
        - TZ=Europe/Moscow
        - PGTZ=Europe/Moscow
        - POSTGRES_DB=pgdb
        - POSTGRES_USER=pgdev
        - POSTGRES_PASSWORD=pgdev
      volumes:
        - "./_db/pg12:/var/lib/postgresql/data"
      networks:
        - pgnet
  pg13:
      image: "postgres:13"
      restart: on-failure
      expose:
        - 5432
      ports:
        - "15013:5432"
      environment:
        - TZ=Europe/Moscow
        - PGTZ=Europe/Moscow
        - POSTGRES_DB=pgdb
        - POSTGRES_USER=pgdev
        - POSTGRES_PASSWORD=pgdev
      volumes:
        - "./_db/pg13:/var/lib/postgresql/data"
      networks:
        - pgnet