#!/usr/bin/env php
<?php
define('YII_ENV', 'prod');
define('YII_DEBUG', false);
require __DIR__.'/vendor/autoload.php';
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');
$config = require(__DIR__ . '/app/config/config.php');

$app = new yii\console\Application($config);
$exitCode = $app->run();
exit($exitCode);
