<?php
return [
    'id' => 'console',

    'basePath' => dirname(__DIR__),
    'vendorPath' => dirname(__DIR__) . '/../vendor',
    'runtimePath' => dirname(__DIR__) . '/runtime/',
    'controllerNamespace' => 'app\console',
    'bootstrap' => ['log', /*'queue'*/],
    'language' => 'ru-RU',
    'components' =>[
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],
        'db' => [
            'class' => yii\db\Connection::class,
            'dsn' => 'pgsql:host=localhost;port=15012;dbname=pgdb',
            'username' => 'pgdev',
            'password' => 'pgdev',
            'charset' => 'utf8',
            'enableSchemaCache' => true,
            'enableQueryCache' => false,
            'schemaCacheDuration' => 3600,
            'schemaCache' => 'cache',
        ],
        'db12' => [
            'class' => yii\db\Connection::class,
            'dsn' => 'pgsql:host=localhost;port=15012;dbname=pgdb',
            'username' => 'pgdev',
            'password' => 'pgdev',
            'charset' => 'utf8',
            'enableSchemaCache' => true,
            'enableQueryCache' => false,
            'schemaCacheDuration' => 3600,
            'schemaCache' => 'cache',
        ],
        'db13' => [
            'class' => yii\db\Connection::class,
            'dsn' => 'pgsql:host=localhost;port=15013;dbname=pgdb',
            'username' => 'pgdev',
            'password' => 'pgdev',
            'charset' => 'utf8',
            'enableSchemaCache' => true,
            'enableQueryCache' => false,
            'schemaCacheDuration' => 3600,
            'schemaCache' => 'cache',
        ],
        'db11' => [
            'class' => yii\db\Connection::class,
            'dsn' => 'pgsql:host=localhost;port=15011;dbname=pgdb',
            'username' => 'pgdev',
            'password' => 'pgdev',
            'charset' => 'utf8',
            'enableSchemaCache' => true,
            'enableQueryCache' => false,
            'schemaCacheDuration' => 3600,
            'schemaCache' => 'cache',
        ],
        'db10' => [
            'class' => yii\db\Connection::class,
            'dsn' => 'pgsql:host=localhost;port=15010;dbname=pgdb',
            'username' => 'pgdev',
            'password' => 'pgdev',
            'charset' => 'utf8',
            'enableSchemaCache' => true,
            'enableQueryCache' => false,
            'schemaCacheDuration' => 3600,
            'schemaCache' => 'cache',
        ],
    ],
    'controllerMap' => [
        'migrate' => [
            'class' => \yii\console\controllers\MigrateController::class,
        ],
    ],
];